name: Build and Upload to S3

on:
  push:
    branches:
      - master # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js (match your Lambda runtime, e.g., 20.x)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Create zip file with code and node_modules
      - name: Create zip file
        run: zip -r lambda-${{ github.sha }}.zip . -x "*.git*"

      # Configure AWS CLI with credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: 'ASIAUNP4QKDYLTJUIZC6'
          aws-secret-access-key: 'h/XUXBuWiVAf46ZEd5Y2jyGS9FY2EGvwfs9k6sb0'
          aws-region: '	us-east-1'

      # Upload zip to S3
      - name: Upload to S3
        run: aws s3 cp lambda-${{ github.sha }}.zip s3://${{ secrets.S3_BUCKET }}/lambda-${{ github.sha }}.zip